/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzw_essayjokestudy_utils_PathchUtils */

#ifndef _Included_com_zzw_essayjokestudy_utils_PathchUtils
#define _Included_com_zzw_essayjokestudy_utils_PathchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzw_essayjokestudy_utils_PathchUtils
 * Method:    combine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zzw_essayjokestudy_utils_PathchUtils_combine
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
